# file Export_MultiTable_5G bao gồm các sheet
 1.NRCELL
 2.INVUNIT

In [39]:
import pandas as pd
import glob

In [21]:
def read_excel_columns(file_path, columns, header_row=0,):
   
    df = pd.read_excel(file_path, header=header_row,engine='openpyxl')
    df = df[[col for col in columns if col in df.columns]]

    return df

In [76]:
# đọc file LST UCELL.xlsx
UCELL_COLUMNS = ["Cell Name", "Cell ID","Downlink UARFCN", 
                 'DL Primary Scrambling Code','Location Area Code','Routing Area Code', "BSC Name", "Logical RNC ID"]
file = 'LST UCELL.xlsx'
ucell_df = read_excel_columns(file, header_row=1, columns=UCELL_COLUMNS)
ucell_df.head()

c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Cell Name,Cell ID,Downlink UARFCN,DL Primary Scrambling Code,Location Area Code,Routing Area Code,BSC Name,Logical RNC ID
0,DTCL01C3CH,35733,10612,435,44411,124,RCTCR12H,422
1,DTLO08C3CD,37634,10612,298,44421,124,RCTCR12H,422
2,DTTM02C3CD,58154,10612,156,44411,124,RCTCR12H,422
3,DTLV15C3CC,38342,10612,13,44421,124,RCTCR12H,422
4,DTLV15C3CA,38341,10612,5,44421,124,RCTCR12H,422

In [78]:
rename_map = {'Cell ID': 'CI','Downlink UARFCN': 'UARFCN',
              'DL Primary Scrambling Code': 'PSC','Location Area Code': 'LAC',
              'Routing Area Code': 'RAC','BSC Name': 'RNC Name', 'Logical RNC ID': 'RNC ID'}
ucell_df = ucell_df.rename(columns=rename_map)
ucell_df.head()

    Cell Name     CI  UARFCN  PSC    LAC  RAC  RNC Name  RNC ID
0  DTCL01C3CH  35733   10612  435  44411  124  RCTCR12H     422
1  DTLO08C3CD  37634   10612  298  44421  124  RCTCR12H     422
2  DTTM02C3CD  58154   10612  156  44411  124  RCTCR12H     422
3  DTLV15C3CC  38342   10612   13  44421  124  RCTCR12H     422
4  DTLV15C3CA  38341   10612    5  44421  124  RCTCR12H     422

In [79]:
ucell_df['Vendor'] = 'Huawei'

In [24]:
# read UtranCell.xlsx file
UTRANCELL_COLUMNS = ["UtranCellId", "cId", "uarfcnDl", "primaryScramblingCode", "locationAreaRef",
                     'routingAreaRef']
file = 'UtranCell.xlsx'
utrancell_df = read_excel_columns(file, columns=UTRANCELL_COLUMNS)
utrancell_df.head()

,UtranCellId,cId,uarfcnDl,primaryScramblingCode,locationAreaRef,routingAreaRef
0,STLP01D,61034,10587,294,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl..."
1,STLP01E,61035,10587,265,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl..."
2,STLP01F,61036,10587,258,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl..."
3,STLP01G,61037,10612,294,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl..."
4,STLP01H,61038,10612,265,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl..."

In [25]:
utrancell_df['RNC Name'] = utrancell_df['locationAreaRef'].str.slice(11,18)
utrancell_df.head()

,UtranCellId,cId,uarfcnDl,primaryScramblingCode,locationAreaRef,routingAreaRef,RNC Name
0,STLP01D,61034,10587,294,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...",RSG104E
1,STLP01E,61035,10587,265,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...",RSG104E
2,STLP01F,61036,10587,258,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...",RSG104E
3,STLP01G,61037,10612,294,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...",RSG104E
4,STLP01H,61038,10612,265,"SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...","SubNetwork=RSG104E,MeContext=RSG104E,ManagedEl...",RSG104E

In [26]:
utrancell_df['locationAreaRef'] = utrancell_df['locationAreaRef'].str.replace(r'^.*LocationArea=','', regex=True)
utrancell_df['routingAreaRef'] = utrancell_df['routingAreaRef'].str.replace(r'^.*RoutingArea=','', regex=True)
utrancell_df.head()

,UtranCellId,cId,uarfcnDl,primaryScramblingCode,locationAreaRef,routingAreaRef,RNC Name
0,STLP01D,61034,10587,294,44700,128,RSG104E
1,STLP01E,61035,10587,265,44700,128,RSG104E
2,STLP01F,61036,10587,258,44700,128,RSG104E
3,STLP01G,61037,10612,294,44700,128,RSG104E
4,STLP01H,61038,10612,265,44700,128,RSG104E

In [27]:
rename_map = {"UtranCellId": "Cell Name", 'cId': 'CI', 'uarfcnDl': 'UARFCN',
              'primaryScramblingCode': 'PSC', 'locationAreaRef': 'LAC', 'routingAreaRef': 'RAC'}
utrancell_df = utrancell_df.rename(columns=rename_map)
utrancell_df.head()

  Cell Name     CI  UARFCN  PSC    LAC  RAC RNC Name
0   STLP01D  61034   10587  294  44700  128  RSG104E
1   STLP01E  61035   10587  265  44700  128  RSG104E
2   STLP01F  61036   10587  258  44700  128  RSG104E
3   STLP01G  61037   10612  294  44700  128  RSG104E
4   STLP01H  61038   10612  265  44700  128  RSG104E

In [28]:
utrancell_df['RNC ID'] = 212
utrancell_df.head()

  Cell Name     CI  UARFCN  PSC    LAC  RAC RNC Name  RNC ID
0   STLP01D  61034   10587  294  44700  128  RSG104E     212
1   STLP01E  61035   10587  265  44700  128  RSG104E     212
2   STLP01F  61036   10587  258  44700  128  RSG104E     212
3   STLP01G  61037   10612  294  44700  128  RSG104E     212
4   STLP01H  61038   10612  265  44700  128  RSG104E     212

In [72]:
utrancell_df['Vendor'] = 'Ericsson'

In [29]:
# read WCEL.xlsx file
WCEL_COLUMNS = ["name", "CId", "UARFCN", "PriScrCode", "LAC",
                'RAC','MO']
file = 'WCEL.xlsx'
wcel_df = read_excel_columns(file, columns=WCEL_COLUMNS)
wcel_df.head()

,name,CId,UARFCN,PriScrCode,LAC,RAC,MO
0,CTNK78G,12117,10612,292,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-7
1,CTNK78H,12118,10612,300,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-8
2,CTNK78I,12119,10612,308,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-9
3,CTTN09G,10777,10612,78,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-7
4,CTTN09H,10778,10612,86,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-8

In [30]:
wcel_df['RNC ID'] = wcel_df['MO'].str.slice(14,17)
wcel_df.head()

,name,CId,UARFCN,PriScrCode,LAC,RAC,MO,RNC ID
0,CTNK78G,12117,10612,292,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-7,402
1,CTNK78H,12118,10612,300,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-8,402
2,CTNK78I,12119,10612,308,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-9,402
3,CTTN09G,10777,10612,78,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-7,402
4,CTTN09H,10778,10612,86,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-8,402

In [ ]:
rnc_id_map = {421:"RCTCR11H",422:"RCTCR12H",417:"RCTCR1N",415:"RCTCR2N",437:"RCTCR3Z",403:"RCTCR4Z",
409:"RCTCR5Z",404:"RCTCR6Z",402:"RCTCR8N",71:"RDNBH3N",603:"RDNBH4E",604:"RDNBH5N",613:"RDNBH6E",407:"RKGRG3Z",408:"RKGRG4Z",217:"RSG011E",218:"RSG072E",224:"RSG091N",
225:"RSG092N",222:"RSG093E",226:"RSG094N",10:"RSG096E",214:"RSG103E",212:"RSG104E",216:"RSGBC2E",210:"RSGBI2E",220:"RSGBT2E",213:"RSGHM1E",
211:"RSGTB2E",412:"RTGMT3N",414:"RTGMT4N",416:"RTGMT5N",600:"RTNTN1N",411:"RVLVL1N",219:"RSG091E",413:"RSG097N",418:"RSG098N",401:"RSG095N",608:"RSG099N"}

In [33]:
wcel_df['RNC Name'] = wcel_df['RNC ID'].astype(int).map(rnc_id_map)
wcel_df.head()

,name,CId,UARFCN,PriScrCode,LAC,RAC,MO,RNC ID,RNC Name
0,CTNK78G,12117,10612,292,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-7,402,RCTCR8N
1,CTNK78H,12118,10612,300,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-8,402,RCTCR8N
2,CTNK78I,12119,10612,308,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-9,402,RCTCR8N
3,CTTN09G,10777,10612,78,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-7,402,RCTCR8N
4,CTTN09H,10778,10612,86,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-8,402,RCTCR8N

In [35]:
rename_map = {"name": "Cell Name", 'CId': 'CI', 'UARFCN': 'UARFCN',
              'PriScrCode': 'PSC', 'LAC': 'LAC', 'RAC': 'RAC'}  
wcel_df = wcel_df.rename(columns=rename_map)
wcel_df.head()

,Cell Name,CI,UARFCN,PSC,LAC,RAC,MO,RNC ID,RNC Name
0,CTNK78G,12117,10612,292,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-7,402,RCTCR8N
1,CTNK78H,12118,10612,300,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-8,402,RCTCR8N
2,CTNK78I,12119,10612,308,43001,54,PLMN-PLMN/RNC-402/WBTS-1/WCEL-9,402,RCTCR8N
3,CTTN09G,10777,10612,78,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-7,402,RCTCR8N
4,CTTN09H,10778,10612,86,43001,54,PLMN-PLMN/RNC-402/WBTS-10/WCEL-8,402,RCTCR8N

In [36]:
wcel_df.drop(columns=['MO'], inplace=True)
wcel_df = wcel_df[['Cell Name', 'CI', 'UARFCN', 'PSC', 'LAC', 'RAC', 'RNC Name', 'RNC ID']]
wcel_df.head()

  Cell Name     CI  UARFCN  PSC    LAC  RAC RNC Name RNC ID
0   CTNK78G  12117   10612  292  43001   54  RCTCR8N    402
1   CTNK78H  12118   10612  300  43001   54  RCTCR8N    402
2   CTNK78I  12119   10612  308  43001   54  RCTCR8N    402
3   CTTN09G  10777   10612   78  43001   54  RCTCR8N    402
4   CTTN09H  10778   10612   86  43001   54  RCTCR8N    402

In [73]:
wcel_df['Vendor'] = 'Nokia'

In [47]:
def read_file_skip_headers(folder,sheet_name,columns=None):
    files = sorted(glob.glob(folder + "/*.xlsx"))
    first_df = pd.read_excel(files[0], sheet_name=sheet_name)
    dfs = [first_df]

    for file in files[1:]:
        d = pd.read_excel(file, sheet_name=sheet_name,header=5)
        d.columns = first_df.columns
        dfs.append(d)
    df_result = pd.concat(dfs, ignore_index=True)
    if columns is not None:
        df_result = df_result[[col for col in columns if col in df_result.columns]]
    return df_result

In [62]:
UUtranCellFDD_COLUMNS = ["userLabel", "cId", "uarfcnDl", "primaryScramblingCode", "refULocationArea",
                     'refURoutingArea','URncFunction']
zte_UUtranCellFDD_df = read_file_skip_headers('D:/Work/Tool/Inventory/3G ZTE',sheet_name='UUtranCellFDD', columns=UUtranCellFDD_COLUMNS)
zte_UUtranCellFDD_df.head()

c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,userLabel,cId,uarfcnDl,primaryScramblingCode,refULocationArea,refURoutingArea,URncFunction
0,User Label,Cell Identity,DUARFCN,Cell Primary Scrambling Code,Used Location Area,Used Routing Area,RNC Configuration Object ID
1,string:[0~80],long:[0~65534],"long:{freqBandInd==0}[10562..10838],{freqBandI...","long:[0~511],[65535~65535]",string:[0~4000],string:[0~4000],long:[0~4095]
2,User Label,Cell Identity,DUARFCN,Cell Primary Scrambling Code,Used Location Area,Used Routing Area,RNC Configuration Object ID
3,R-W,R-W-I,R-W-I,R-W-I,R-W-I,R-W-I,Primary Key
4,BLHD41I,4669,10612,386,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404

In [64]:
zte_UUtranCellFDD_df.drop(index=[0,1,2,3], inplace=True)
zte_UUtranCellFDD_df.head()

,userLabel,cId,uarfcnDl,primaryScramblingCode,refULocationArea,refURoutingArea,URncFunction
4,BLHD41I,4669,10612,386,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404
5,BLPL39G,4727,10612,163,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404
6,BLHD42G,4677,10612,109,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404
7,BLHD42H,4678,10612,101,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404
8,BLHD42I,4679,10612,117,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...","SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404

In [54]:
# read sheet ULocationArea
zte_ULocationArea_df = read_file_skip_headers('D:/Work/Tool/Inventory/3G ZTE',sheet_name='ULocationArea')
zte_ULocationArea_df.drop(index=[0,1,2,3], inplace=True)
zte_ULocationArea_df.head()

c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,MODIND,MOI,SubNetwork,MEID,URncFunction,ULocationArea,userLabel,description,lac,reservedByUSnac
4,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,34502,NaN,LAC=34502,34502,NaN
5,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,44202,NaN,LAC=44202,44202,NaN
6,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,44720,NaN,LAC=44720,44720,NaN
7,P,"SubNetwork=403,MEID=403,URncFunction=403,ULoca...",403,403,403,44710,NaN,LAC=44710,44710,NaN
8,P,"SubNetwork=403,MEID=403,URncFunction=403,ULoca...",403,403,403,65014,NaN,LAC=65014,65014,NaN

In [55]:
# read sheet URoutingArea
zte_URoutingArea_df = read_file_skip_headers('D:/Work/Tool/Inventory/3G ZTE',sheet_name='URoutingArea')
zte_URoutingArea_df.drop(index=[0,1,2,3], inplace=True)
zte_URoutingArea_df.head()

c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Chinhnq\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,MODIND,MOI,SubNetwork,MEID,URncFunction,ULocationArea,URoutingArea,userLabel,description,rac
4,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,34502,107,NaN,"LAC=34502,RAC=107",107
5,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,44202,127,NaN,"LAC=44202,RAC=127",127
6,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,44720,127,NaN,"LAC=44720,RAC=127",127
7,P,"SubNetwork=404,MEID=404,URncFunction=404,ULoca...",404,404,404,44720,128,NaN,"LAC=44720,RAC=128",128
8,P,"SubNetwork=403,MEID=403,URncFunction=403,ULoca...",403,403,403,44710,128,NaN,"LAC=44710,RAC=128",128

In [56]:
zte_ULocationArea_df = zte_ULocationArea_df[['MOI','lac']]
zte_URoutingArea_df = zte_URoutingArea_df[['MOI','rac']]
zte_URoutingArea_df.head()

                                                 MOI  rac
4  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  107
5  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  127
6  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  127
7  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  128
8  SubNetwork=403,MEID=403,URncFunction=403,ULoca...  128

In [57]:
zte_ULocationArea_df.head()

                                                 MOI    lac
4  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  34502
5  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  44202
6  SubNetwork=404,MEID=404,URncFunction=404,ULoca...  44720
7  SubNetwork=403,MEID=403,URncFunction=403,ULoca...  44710
8  SubNetwork=403,MEID=403,URncFunction=403,ULoca...  65014

In [66]:
zte_cell_df = pd.merge(zte_UUtranCellFDD_df, zte_ULocationArea_df, left_on='refULocationArea', right_on='MOI', how='left')
zte_cell_df.drop(columns=['MOI'], inplace=True)
zte_cell_df = pd.merge(zte_cell_df, zte_URoutingArea_df, left_on='refURoutingArea', right_on='MOI', how='left')
zte_cell_df.drop(columns=['MOI','refULocationArea','refURoutingArea'], inplace=True)
zte_cell_df.head()

  userLabel   cId uarfcnDl primaryScramblingCode URncFunction    lac  rac
0   BLHD41I  4669    10612                   386          404  44202  127
1   BLPL39G  4727    10612                   163          404  44202  127
2   BLHD42G  4677    10612                   109          404  44202  127
3   BLHD42H  4678    10612                   101          404  44202  127
4   BLHD42I  4679    10612                   117          404  44202  127

In [67]:
zte_cell_df['RNC Name'] = zte_cell_df['URncFunction'].astype(int).map(rnc_id_map)
zte_cell_df.head()

,userLabel,cId,uarfcnDl,primaryScramblingCode,URncFunction,lac,rac,RNC Name
0,BLHD41I,4669,10612,386,404,44202,127,RCTCR6Z
1,BLPL39G,4727,10612,163,404,44202,127,RCTCR6Z
2,BLHD42G,4677,10612,109,404,44202,127,RCTCR6Z
3,BLHD42H,4678,10612,101,404,44202,127,RCTCR6Z
4,BLHD42I,4679,10612,117,404,44202,127,RCTCR6Z

In [69]:
rename_map = {'userLabel': 'Cell Name', 'cId': 'CI', 'uarfcnDl': 'UARFCN',
              'primaryScramblingCode': 'PSC', 'lac': 'LAC', 'rac': 'RAC','URncFunction': 'RNC ID'}
zte_cell_df = zte_cell_df.rename(columns=rename_map)
zte_cell_df.head()

  Cell Name    CI UARFCN  PSC RNC ID    LAC  RAC RNC Name
0   BLHD41I  4669  10612  386    404  44202  127  RCTCR6Z
1   BLPL39G  4727  10612  163    404  44202  127  RCTCR6Z
2   BLHD42G  4677  10612  109    404  44202  127  RCTCR6Z
3   BLHD42H  4678  10612  101    404  44202  127  RCTCR6Z
4   BLHD42I  4679  10612  117    404  44202  127  RCTCR6Z

In [70]:
zte_cell_df = zte_cell_df[['Cell Name', 'CI', 'UARFCN', 'PSC', 'LAC', 'RAC', 'RNC Name', 'RNC ID']]
zte_cell_df.head()

  Cell Name    CI UARFCN  PSC    LAC  RAC RNC Name RNC ID
0   BLHD41I  4669  10612  386  44202  127  RCTCR6Z    404
1   BLPL39G  4727  10612  163  44202  127  RCTCR6Z    404
2   BLHD42G  4677  10612  109  44202  127  RCTCR6Z    404
3   BLHD42H  4678  10612  101  44202  127  RCTCR6Z    404
4   BLHD42I  4679  10612  117  44202  127  RCTCR6Z    404

In [74]:
zte_cell_df['Vendor'] = 'ZTE'

In [80]:
df_final = pd.concat([ucell_df, utrancell_df, wcel_df, zte_cell_df], ignore_index=True)
df_final.head()

    Cell Name     CI UARFCN  PSC    LAC  RAC  RNC Name RNC ID  Vendor
0  DTCL01C3CH  35733  10612  435  44411  124  RCTCR12H    422  Huawei
1  DTLO08C3CD  37634  10612  298  44421  124  RCTCR12H    422  Huawei
2  DTTM02C3CD  58154  10612  156  44411  124  RCTCR12H    422  Huawei
3  DTLV15C3CC  38342  10612   13  44421  124  RCTCR12H    422  Huawei
4  DTLV15C3CA  38341  10612    5  44421  124  RCTCR12H    422  Huawei

In [81]:
df_final.to_excel('3G_inventory_final.xlsx', index=False)