# file Export_MultiTable bao gồm các sheet
 1.LNCEL_FDD
 2.LNCEL
 3.INVUNIT
 4.CHANNEL

In [11]:
import pandas as pd

In [12]:
def read_excel_columns(file_path, sheet,columns):
   
    df = pd.read_excel(file_path, sheet_name=sheet, usecols=columns,  engine='openpyxl')

    return df

In [13]:
# read LNCEL_FDD
LNCEL_FDD_COLUMNS = ["distName", "earfcnDL", "prachCS", "rootSeqIndex", "dlChBw", "dlMimoMode"]
file = 'Export_MultiTable.xlsx'
LNCEL_FDD_DF = read_excel_columns(file, 'LNCEL_FDD', LNCEL_FDD_COLUMNS)
LNCEL_FDD_DF.head()

,distName,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-11/L...,20 MHz,Closed Loop Mimo,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-12/L...,20 MHz,Closed Loop Mimo,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-13/L...,20 MHz,Closed Loop Mimo,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-14/L...,20 MHz,Closed Loop Mimo,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-16/L...,20 MHz,Closed Loop Mimo,1501,10,238

In [15]:
LNCEL_FDD_DF['distName'] = LNCEL_FDD_DF['distName'].astype(str).str.replace('/LNCEL_FDD-0', '', regex=False)

In [16]:
LNCEL_FDD_DF.head()

,distName,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-11,20 MHz,Closed Loop Mimo,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-12,20 MHz,Closed Loop Mimo,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-13,20 MHz,Closed Loop Mimo,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-14,20 MHz,Closed Loop Mimo,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-16,20 MHz,Closed Loop Mimo,1501,10,238

In [17]:
# Đổi tên các giá trị trong cột dlMimoMode
replace_dict = {
    'Closed Loop Mimo': '2T2R',
    'Closed Loop MIMO (4x4)': '4T4R',
    'SingleTX': '1T1R'
}
LNCEL_FDD_DF['dlMimoMode'] = LNCEL_FDD_DF['dlMimoMode'].replace(replace_dict)
LNCEL_FDD_DF.head()

,distName,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-11,20 MHz,2T2R,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-12,20 MHz,2T2R,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-13,20 MHz,2T2R,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-14,20 MHz,2T2R,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-16,20 MHz,2T2R,1501,10,238

In [56]:
# read LNCEL
LNCEL_COLUMNS = ["distName", "cellName", "phyCellId",'tac']

LNCEL_DF = read_excel_columns(file, 'LNCEL', LNCEL_COLUMNS)
LNCEL_DF.head()

                                       distName    cellName  phyCellId    tac
0  PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-11  VUCO03C4BA        205  62180
1  PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-12  VUCO03C4BB        206  62180
2  PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-13  VUCO03C4BC        204  62180
3  PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-14  BDDA16M4BG         93  62240
4  PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-16  BDDA16M4BI         95  62240

In [59]:
df_final = pd.merge(LNCEL_DF, LNCEL_FDD_DF, on='distName', how='inner')
df_final.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238

In [60]:
# read INVUNIT
INVUNIT_COLUMNS = ["distName", "configDN", "inventoryUnitType"]

INVUNIT_DF = read_excel_columns(file, 'INVUNIT', INVUNIT_COLUMNS)
INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-531003/HW-1/INVUNIT-1,MRBTS-531003/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-531003/HW-1/INVUNIT-10,NaN,FAN
2,PLMN-PLMN/MRBTS-531003/HW-1/INVUNIT-11,NaN,FAN
3,PLMN-PLMN/MRBTS-531003/HW-1/INVUNIT-12,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU
4,PLMN-PLMN/MRBTS-531003/HW-1/INVUNIT-13,NaN,FAN

In [62]:
INVUNIT_DF['distName'] = INVUNIT_DF['distName'].astype(str).str.replace(r'/HW.*$', '', regex=True)   
INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-531003,NaN,FAN
2,PLMN-PLMN/MRBTS-531003,NaN,FAN
3,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU
4,PLMN-PLMN/MRBTS-531003,NaN,FAN

In [63]:
# Đổi tên các giá trị trong cột inventoryUnitType
replace_dict = {
    'Flexi Baseband Sub-Module FBBC': 'FBBC',
    'Flexi System Module Outdoor FSMF': 'FSMF',
    'BB Extension Outdoor Sub-Module FBBA': 'FBBA'
}
INVUNIT_DF['inventoryUnitType'] = INVUNIT_DF['inventoryUnitType'].replace(replace_dict)
INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-531003,NaN,FAN
2,PLMN-PLMN/MRBTS-531003,NaN,FAN
3,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU
4,PLMN-PLMN/MRBTS-531003,NaN,FAN

In [64]:
# Chỉ giữ lại các giá trị inventoryUnitType mong muốn trong INVUNIT_DF và tách thành 2 DataFrame riêng cho BB và RF
BB_unit_types = ['FBBC', 'FSMF','FBBA']
RF_unit_types = ['FHEL', 'AHEB', 'FRGY', 'FXED', 'FRGU', 'FRGX', 'FRHC', 'FRGT',  'FRGP']
BB_INVUNIT_DF = INVUNIT_DF[INVUNIT_DF['inventoryUnitType'].isin(BB_unit_types)]
BB_INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
5,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC
6,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC
7,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF
14,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC
15,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF

In [65]:
RF_INVUNIT_DF = INVUNIT_DF[INVUNIT_DF['inventoryUnitType'].isin(RF_unit_types)]
RF_INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
3,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU
12,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED
20,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/RMOD-1,FXED
33,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-2,FRGU
36,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-3,AHEB

In [66]:
BB_INVUNIT_DF['BB_count'] = BB_INVUNIT_DF.groupby(['distName','inventoryUnitType'])['inventoryUnitType'].transform('count')
BB_INVUNIT_DF.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_24496\2323968223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BB_INVUNIT_DF['BB_count'] = BB_INVUNIT_DF.groupby(['distName','inventoryUnitType'])['inventoryUnitType'].transform('count')

,distName,configDN,inventoryUnitType,BB_count
5,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,2
6,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC,2
7,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1
14,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,1
15,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1

In [67]:
BB_INVUNIT_DF.to_excel('BB_INVUNIT_DF_4G_NSN.xlsx', index=False)

In [68]:
BB_INVUNIT_DF['BB_map'] = BB_INVUNIT_DF['BB_count'].astype(str) + '_' + BB_INVUNIT_DF['inventoryUnitType']
BB_INVUNIT_DF.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_24496\3052174421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BB_INVUNIT_DF['BB_map'] = BB_INVUNIT_DF['BB_count'].astype(str) + '_' + BB_INVUNIT_DF['inventoryUnitType']

,distName,configDN,inventoryUnitType,BB_count,BB_map
5,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,2,2_FBBC
6,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC,2,2_FBBC
7,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
14,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,1,1_FBBC
15,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF

In [69]:
# Sắp xếp BB_INVUNIT_DF theo inventoryUnitType giảm dần
BB_INVUNIT_DF = BB_INVUNIT_DF.sort_values(by=['inventoryUnitType','distName'], ascending=False)
BB_INVUNIT_DF.head()

,distName,configDN,inventoryUnitType,BB_count,BB_map
76359,PLMN-PLMN/MRBTS-897002,MRBTS-897002/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
76128,PLMN-PLMN/MRBTS-897001,MRBTS-897001/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
76452,PLMN-PLMN/MRBTS-897000,MRBTS-897000/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
75553,PLMN-PLMN/MRBTS-896321,MRBTS-896321/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
75793,PLMN-PLMN/MRBTS-896320,MRBTS-896320/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF

In [71]:
BB_INVUNIT_DF = BB_INVUNIT_DF[['distName', 'BB_map']].drop_duplicates()
BB_INVUNIT_DF.head()

                     distName  BB_map
76359  PLMN-PLMN/MRBTS-897002  1_FSMF
76128  PLMN-PLMN/MRBTS-897001  1_FSMF
76452  PLMN-PLMN/MRBTS-897000  1_FSMF
75553  PLMN-PLMN/MRBTS-896321  1_FSMF
75793  PLMN-PLMN/MRBTS-896320  1_FSMF

In [72]:
BB_INVUNIT_DF['BB_configDN'] = BB_INVUNIT_DF.groupby(['distName'])['BB_map'].transform(lambda x: ' + '.join(x))
BB_INVUNIT_DF.head()

                     distName  BB_map      BB_configDN
76359  PLMN-PLMN/MRBTS-897002  1_FSMF  1_FSMF + 1_FBBC
76128  PLMN-PLMN/MRBTS-897001  1_FSMF  1_FSMF + 1_FBBC
76452  PLMN-PLMN/MRBTS-897000  1_FSMF  1_FSMF + 1_FBBC
75553  PLMN-PLMN/MRBTS-896321  1_FSMF  1_FSMF + 1_FBBC
75793  PLMN-PLMN/MRBTS-896320  1_FSMF  1_FSMF + 2_FBBC

In [73]:
RF_INVUNIT_DF.head()

,distName,configDN,inventoryUnitType
3,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU
12,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED
20,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/RMOD-1,FXED
33,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-2,FRGU
36,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-3,AHEB

In [74]:
RF_INVUNIT_DF.to_excel('RF_INVUNIT_DF_4G_NSN.xlsx', index=False)

In [76]:
RF_INVUNIT_DF['RMOD'] = RF_INVUNIT_DF['configDN'].astype(str).str.replace(r'^.*/', '', regex=True)   
RF_INVUNIT_DF.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_24496\3165565714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RF_INVUNIT_DF['RMOD'] = RF_INVUNIT_DF['configDN'].astype(str).str.replace(r'^.*/', '', regex=True)

,distName,configDN,inventoryUnitType,RMOD
3,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-1,FRGU,RMOD-1
12,PLMN-PLMN/MRBTS-531003,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
20,PLMN-PLMN/MRBTS-531921,MRBTS-531921/EQM-1/APEQM-1/RMOD-1,FXED,RMOD-1
33,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-2,FRGU,RMOD-2
36,PLMN-PLMN/MRBTS-531867,MRBTS-531867/EQM-1/APEQM-1/RMOD-3,AHEB,RMOD-3

In [77]:
RF_INVUNIT_DF.drop(columns=['distName'], inplace=True)
RF_INVUNIT_DF.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_24496\1955427958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RF_INVUNIT_DF.drop(columns=['distName'], inplace=True)

                             configDN inventoryUnitType    RMOD
3   MRBTS-531003/EQM-1/APEQM-1/RMOD-1              FRGU  RMOD-1
12  MRBTS-531003/EQM-1/APEQM-1/RMOD-2              FXED  RMOD-2
20  MRBTS-531921/EQM-1/APEQM-1/RMOD-1              FXED  RMOD-1
33  MRBTS-531867/EQM-1/APEQM-1/RMOD-2              FRGU  RMOD-2
36  MRBTS-531867/EQM-1/APEQM-1/RMOD-3              AHEB  RMOD-3

In [78]:
# read CHANNEL
CHANNEL_COLUMNS = ["distName", "antlDN", "direction"]

CHANNEL_DF = read_excel_columns(file, 'CHANNEL', CHANNEL_COLUMNS)
CHANNEL_DF.head()

,distName,antlDN,direction
0,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-1,TX
1,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-1,RX
2,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-2,TX
3,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-2,RX
4,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-4,TX

In [79]:
CHANNEL_DF = CHANNEL_DF[CHANNEL_DF['direction'].isin(['TX'])]
CHANNEL_DF.head()

,distName,antlDN,direction
0,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-1,TX
2,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-2,TX
4,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-4,TX
6,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-3,TX
8,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1/ANTL-5,TX

In [80]:
CHANNEL_DF['antlDN'] = CHANNEL_DF['antlDN'].astype(str).str.replace(r'/AN.*$', '', regex=True)   
CHANNEL_DF.head()

,distName,antlDN,direction
0,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1,TX
2,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1,TX
4,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1,TX
6,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1,TX
8,PLMN-PLMN/MRBTS-521504/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-521504/EQM-1/APEQM-1/RMOD-1,TX

In [81]:
df_final_2  = pd.merge(CHANNEL_DF,RF_INVUNIT_DF, left_on='antlDN', right_on='configDN', how='inner')
df_final_2.head()

,distName,antlDN,direction,configDN,inventoryUnitType,RMOD
0,PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
1,PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
2,PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
3,PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
4,PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-531003/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2

In [82]:
df_final_2.drop(columns=['antlDN','direction','configDN'], inplace=True)
df_final_2.head()

                                            distName inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
1  PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
3  PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-531003/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2

In [83]:
df_final_2['distName'] = df_final_2['distName'].astype(str).str.replace('/MNL-1/MNLENT-1/CELLMAPPING-1', '', regex=False)
df_final_2.head()

                                            distName inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-531003/LCELL-11/CHANNELGROUP-1...              FXED  RMOD-2
1  PLMN-PLMN/MRBTS-531003/LCELL-11/CHANNELGROUP-1...              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-531003/LCELL-12/CHANNELGROUP-1...              FXED  RMOD-2
3  PLMN-PLMN/MRBTS-531003/LCELL-12/CHANNELGROUP-1...              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-531003/LCELL-13/CHANNELGROUP-1...              FXED  RMOD-2

In [85]:
df_final_2['distName'] = df_final_2['distName'].astype(str).str.replace(r'/CHAN.*$', '', regex=True)
df_final_2.drop_duplicates(inplace=True)
df_final_2.head()

                          distName inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-531003/LCELL-11              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-531003/LCELL-12              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-531003/LCELL-13              FXED  RMOD-2
6  PLMN-PLMN/MRBTS-531003/LCELL-17              FRGU  RMOD-1
8  PLMN-PLMN/MRBTS-531003/LCELL-18              FRGU  RMOD-1

In [98]:
df_final_2['distName'] = df_final_2['distName'].astype(str).str.replace('LCELL','LNCEL',regex=False)
df_final_2.head()

                          distName inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-531003/LNCEL-11              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-531003/LNCEL-12              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-531003/LNCEL-13              FXED  RMOD-2
6  PLMN-PLMN/MRBTS-531003/LNCEL-17              FRGU  RMOD-1
8  PLMN-PLMN/MRBTS-531003/LNCEL-18              FRGU  RMOD-1

In [100]:
df_final.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238

In [102]:
df_final['distName'] = df_final['distName'].astype(str).str.replace(r'LNBTS.*/','', regex=True)
df_final.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238

In [111]:
df_final_3 = pd.merge(df_final,df_final_2,on='distName', how='left')
df_final_3.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,inventoryUnitType,RMOD
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762,NaN,NaN
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720,NaN,NaN
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528,NaN,NaN
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166,AHEB,RMOD-3
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238,AHEB,RMOD-4

In [112]:
df_final_3["eNodeB_id"] = df_final_3['distName'].astype(str).str.replace(r'/LNCEL-(\d+)', '', regex=True)
df_final_3.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,inventoryUnitType,RMOD,eNodeB_id
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762,NaN,NaN,PLMN-PLMN/MRBTS-521504
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720,NaN,NaN,PLMN-PLMN/MRBTS-521504
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528,NaN,NaN,PLMN-PLMN/MRBTS-521504
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166,AHEB,RMOD-3,PLMN-PLMN/MRBTS-531867
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238,AHEB,RMOD-4,PLMN-PLMN/MRBTS-531867

In [113]:
# Tạo cột Band trong df_final_3 dựa trên giá trị earfcnDL
band_map = {1501: 3, 1874: 3, 50: 1, 3150: 7, 1300:3}
df_final_3['Band'] = df_final_3['earfcnDL'].map(band_map)
df_final_3.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,inventoryUnitType,RMOD,eNodeB_id,Band
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166,AHEB,RMOD-3,PLMN-PLMN/MRBTS-531867,3.0
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238,AHEB,RMOD-4,PLMN-PLMN/MRBTS-531867,3.0

In [114]:
df_final_3['RF type Count'] = df_final_3.groupby(['eNodeB_id','RMOD','inventoryUnitType','Band'])['inventoryUnitType'].transform('count')
df_final_3.head()

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,inventoryUnitType,RMOD,eNodeB_id,Band,RF type Count
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0,NaN
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0,NaN
2,PLMN-PLMN/MRBTS-521504/LNCEL-13,VUCO03C4BC,204,62180,20 MHz,2T2R,1501,10,528,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0,NaN
3,PLMN-PLMN/MRBTS-531867/LNCEL-14,BDDA16M4BG,93,62240,20 MHz,2T2R,1501,10,166,AHEB,RMOD-3,PLMN-PLMN/MRBTS-531867,3.0,2.0
4,PLMN-PLMN/MRBTS-531867/LNCEL-16,BDDA16M4BI,95,62240,20 MHz,2T2R,1501,10,238,AHEB,RMOD-4,PLMN-PLMN/MRBTS-531867,3.0,2.0

In [115]:
import numpy as np
df_final_3['RF_Type_Count_Inv'] = np.where(
    df_final_3['RF type Count'] == 1, "1",
    np.where(df_final_3['RF type Count'] == 2, "0.5",
    np.where(df_final_3['RF type Count'] == 4, "0.25",
    np.where(df_final_3['RF type Count'] == 6, "1/6",       
    np.where(df_final_3['RF type Count'] == 3, "1/3", 1/df_final_3['RF type Count'])))))
df_final_3.head(2)

,distName,cellName,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,inventoryUnitType,RMOD,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv
0,PLMN-PLMN/MRBTS-521504/LNCEL-11,VUCO03C4BA,205,62180,20 MHz,2T2R,1501,10,762,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0,NaN,nan
1,PLMN-PLMN/MRBTS-521504/LNCEL-12,VUCO03C4BB,206,62180,20 MHz,2T2R,1501,10,720,NaN,NaN,PLMN-PLMN/MRBTS-521504,3.0,NaN,nan

In [108]:
df_final_3['Config_RRU_per_Cell'] = df_final_3['RF_Type_Count_Inv'].astype(str) + '_' + df_final_3['inventoryUnitType'].astype(str)
df_final_3.head()

KeyError: 'RF_Type_Count_Inv'

In [55]:
df_final_3['Config_RRU'] = (df_final_3.groupby(['distName','name'])['Config_RRU_per_Cell'].transform(lambda x: "+".join(map(str, x))))

KeyError: 'Column not found: Config_RRU_per_Cell'

In [ ]:
df_final_3 = df_final_3.sort_values(by='RMOD',ascending=True)
df_final_3['Subrack'] = (df_final_3.groupby(['MO','name'])['RMOD'].transform(lambda x: "+".join(map(str, x))))
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack
30634,PLMN-PLMN/MRBTS-894005/LNCEL-13,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,642.0,PLMN-PLMN/MRBTS-894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1
11389,PLMN-PLMN/MRBTS-562484/LNCEL-12,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,222.0,PLMN-PLMN/MRBTS-562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2
22792,PLMN-PLMN/MRBTS-600622/LNCEL-43,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,12.0,PLMN-PLMN/MRBTS-600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2
11392,PLMN-PLMN/MRBTS-562484/LNCEL-13,FXED,RMOD-1,DNTN45C4BC,50.0,65160.0,20 MHz,4T4R,1501.0,10.0,384.0,PLMN-PLMN/MRBTS-562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2
11393,PLMN-PLMN/MRBTS-562951/LNCEL-11,FXED,RMOD-1,DNDQ00M4BA,222.0,65110.0,20 MHz,2T2R,1501.0,10.0,66.0,PLMN-PLMN/MRBTS-562951,3.0,4.0,0.25,0.25_FXED,0.25_FXED,RMOD-1

In [ ]:
df_final_3['localcell ID'] = df_final_3['distName'].replace(r'^.*-', '', regex=True)

In [ ]:

df_final_3['eNodeB_id'] = df_final_3['eNodeB_id'].replace(r'^.*-', '', regex=True)
df_final_3['MO'] = df_final_3['MO'].replace(r'/LN.*', '', regex=True)
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,localcell ID
30634,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,642.0,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13
11389,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,222.0,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12
22792,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,12.0,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43
11392,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BC,50.0,65160.0,20 MHz,4T4R,1501.0,10.0,384.0,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,13
11393,PLMN-PLMN/MRBTS-562951,FXED,RMOD-1,DNDQ00M4BA,222.0,65110.0,20 MHz,2T2R,1501.0,10.0,66.0,562951,3.0,4.0,0.25,0.25_FXED,0.25_FXED,RMOD-1,11

In [ ]:
df_final_3['Vendor']= 'Nokia'

In [ ]:
df_final_4 = pd.merge(df_final_3, BB_INVUNIT_DF[['MO', 'BB_configDN']], on='distName', how='left')
df_final_4.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,...,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,localcell ID,Vendor,BB_configDN
0,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
1,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
2,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
3,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
4,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,...,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43,Nokia,1_FSMF + 1_FBBC

In [ ]:
rename_columns = {'name':'Cell Name', 'phyCellId':'PCI', 'earfcnDL':'EARFCN',
                  'dlChBw':'Bandwidth', 'dlMimoMode':'MIMO','rootSeqIndex':'RSI', 'tac':'TAC',
                  'BB_configDN':'Config_BBU','prachCS':'Cell Radius','localcell ID':'Local Cell ID','distName':'Base Station Name',
                  'eNodeB_id':'eNodeB ID'
                  } 
df_final_4.rename(columns=rename_columns, inplace=True)
df_final_4.head()

,Base Station Name,inventoryUnitType,RMOD,Cell Name,PCI,TAC,Bandwidth,MIMO,EARFCN,Cell Radius,...,eNodeB ID,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,Local Cell ID,Vendor,Config_BBU
0,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
1,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
2,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
3,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
4,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,...,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43,Nokia,1_FSMF + 1_FBBC

In [ ]:
df_final_Nokia = df_final_4[['Base Station Name', 'Local Cell ID', 'Cell Name', 'Band', 'EARFCN',
       'Bandwidth', 'MIMO','eNodeB ID', 'TAC', 'PCI', 'RSI', 'Cell Radius', 'Vendor', 'Subrack', 'Config_BBU', 'Config_RRU']]
df_final_Nokia.head()

,Base Station Name,Local Cell ID,Cell Name,Band,EARFCN,Bandwidth,MIMO,eNodeB ID,TAC,PCI,RSI,Cell Radius,Vendor,Subrack,Config_BBU,Config_RRU
0,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
1,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
2,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
3,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
4,PLMN-PLMN/MRBTS-600622,43,TYTR78C4BL,3.0,1874.0,15 MHz,2T2R,600622,62890.0,417.0,12.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/6_FXED+1/6_FXED

In [ ]:
df_final_Nokia['Local Cell ID']= df_final_Nokia['Local Cell ID'].astype(int)
df_final_Nokia['eNodeB ID']= df_final_Nokia['eNodeB ID'].astype(int)
df_final_Nokia.drop_duplicates(inplace=True)
df_final_Nokia.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia['Local Cell ID']= df_final_Nokia['Local Cell ID'].astype(int)
C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia['eNodeB ID']= df_final_Nokia['eNodeB ID'].astype(int)
C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia.drop_duplicates(inplace=True)

,Base Station Name,Local Cell ID,Cell Name,Band,EARFCN,Bandwidth,MIMO,eNodeB ID,TAC,PCI,RSI,Cell Radius,Vendor,Subrack,Config_BBU,Config_RRU
0,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
2,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
4,PLMN-PLMN/MRBTS-600622,43,TYTR78C4BL,3.0,1874.0,15 MHz,2T2R,600622,62890.0,417.0,12.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/6_FXED+1/6_FXED
6,PLMN-PLMN/MRBTS-562484,13,DNTN45C4BC,3.0,1501.0,20 MHz,4T4R,562484,65160.0,50.0,384.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
8,PLMN-PLMN/MRBTS-562951,11,DNDQ00M4BA,3.0,1501.0,20 MHz,2T2R,562951,65110.0,222.0,66.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,0.25_FXED

In [ ]:
df_final_Nokia.to_excel('4G_NSN_Inventory_Output.xlsx', index=False)