# file Export_MultiTable bao gồm các sheet
 1.LNCEL_FDD
 2.LNCEL
 3.INVUNIT
 4.CHANNEL

In [1]:
import pandas as pd

In [2]:
def read_excel_columns(file_path, sheet,columns):
   
    df = pd.read_excel(file_path, sheet_name=sheet, usecols=columns,  engine='openpyxl')

    return df

In [3]:
# read LNCEL_FDD
LNCEL_FDD_COLUMNS = ["MO", "earfcnDL", "prachCS", "rootSeqIndex", "dlChBw", "dlMimoMode"]
file = 'Export_MultiTable.xlsx'
LNCEL_FDD_DF = read_excel_columns(file, 'LNCEL_FDD', LNCEL_FDD_COLUMNS)
LNCEL_FDD_DF.head()

,MO,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11/L...,20 MHz,Closed Loop Mimo,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12/L...,20 MHz,Closed Loop MIMO (4x4),1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13/L...,20 MHz,Closed Loop Mimo,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17/L...,10 MHz,Closed Loop Mimo,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18/L...,10 MHz,Closed Loop Mimo,50,10,402

In [4]:
LNCEL_FDD_DF['MO'] = LNCEL_FDD_DF['MO'].astype(str).str.replace('/LNCEL_FDD-0', '', regex=False)

In [5]:
LNCEL_FDD_DF.head()

,MO,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11,20 MHz,Closed Loop Mimo,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12,20 MHz,Closed Loop MIMO (4x4),1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13,20 MHz,Closed Loop Mimo,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17,10 MHz,Closed Loop Mimo,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18,10 MHz,Closed Loop Mimo,50,10,402

In [6]:
# Đổi tên các giá trị trong cột dlMimoMode
replace_dict = {
    'Closed Loop Mimo': '2T2R',
    'Closed Loop MIMO (4x4)': '4T4R',
    'SingleTX': '1T1R'
}
LNCEL_FDD_DF['dlMimoMode'] = LNCEL_FDD_DF['dlMimoMode'].replace(replace_dict)
LNCEL_FDD_DF.head()

,MO,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11,20 MHz,2T2R,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12,20 MHz,4T4R,1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13,20 MHz,2T2R,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17,10 MHz,2T2R,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18,10 MHz,2T2R,50,10,402

In [7]:
# read LNCEL
LNCEL_COLUMNS = ["MO", "name", "phyCellId",'tac']

LNCEL_DF = read_excel_columns(file, 'LNCEL', LNCEL_COLUMNS)
LNCEL_DF.head()

                                             MO        name  phyCellId    tac
0  PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11  VUTT98C4BA        198  62150
1  PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12  VUTT98C4BB        200  62150
2  PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13  VUTT98C4BC        196  62150
3  PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17  VUTT98C4CA        198  62150
4  PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18  VUTT98C4CB        200  62150

In [8]:
df_final = pd.merge(LNCEL_DF, LNCEL_FDD_DF, on='MO', how='inner')
df_final.head()

,MO,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11,VUTT98C4BA,198,62150,20 MHz,2T2R,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12,VUTT98C4BB,200,62150,20 MHz,4T4R,1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13,VUTT98C4BC,196,62150,20 MHz,2T2R,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17,VUTT98C4CA,198,62150,10 MHz,2T2R,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18,VUTT98C4CB,200,62150,10 MHz,2T2R,50,10,402

In [9]:
# read INVUNIT
INVUNIT_COLUMNS = ["MO", "configDN", "inventoryUnitType"]

INVUNIT_DF = read_excel_columns(file, 'INVUNIT', INVUNIT_COLUMNS)
INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-520106/HW-1/INVUNIT-1,MRBTS-520106/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-520106/HW-1/INVUNIT-10,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED
2,PLMN-PLMN/MRBTS-520106/HW-1/INVUNIT-11,NaN,FAN
3,PLMN-PLMN/MRBTS-520106/HW-1/INVUNIT-12,NaN,FAN
4,PLMN-PLMN/MRBTS-520106/HW-1/INVUNIT-13,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU

In [10]:
INVUNIT_DF['MO'] = INVUNIT_DF['MO'].astype(str).str.replace(r'/HW.*$', '', regex=True)   
INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED
2,PLMN-PLMN/MRBTS-520106,NaN,FAN
3,PLMN-PLMN/MRBTS-520106,NaN,FAN
4,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU

In [11]:
# Đổi tên các giá trị trong cột inventoryUnitType
replace_dict = {
    'Flexi Baseband Sub-Module FBBC': 'FBBC',
    'Flexi System Module Outdoor FSMF': 'FSMF',
    'BB Extension Outdoor Sub-Module FBBA': 'FBBA'
}
INVUNIT_DF['inventoryUnitType'] = INVUNIT_DF['inventoryUnitType'].replace(replace_dict)
INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
0,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1,CABINET
1,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED
2,PLMN-PLMN/MRBTS-520106,NaN,FAN
3,PLMN-PLMN/MRBTS-520106,NaN,FAN
4,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU

In [12]:
# Chỉ giữ lại các giá trị inventoryUnitType mong muốn trong INVUNIT_DF và tách thành 2 DataFrame riêng cho BB và RF
BB_unit_types = ['FBBC', 'FSMF','FBBA']
RF_unit_types = ['FHEL', 'AHEB', 'FRGY', 'FXED', 'FRGU', 'FRGX', 'FRHC', 'FRGT',  'FRGP']
BB_INVUNIT_DF = INVUNIT_DF[INVUNIT_DF['inventoryUnitType'].isin(BB_unit_types)]
BB_INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
11,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC
13,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC
14,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF
21,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC
22,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF

In [13]:
RF_INVUNIT_DF = INVUNIT_DF[INVUNIT_DF['inventoryUnitType'].isin(RF_unit_types)]
RF_INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
1,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED
4,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU
7,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,FXED
9,PLMN-PLMN/MRBTS-520106,NaN,FXED
27,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/RMOD-1,FXED

In [14]:
BB_INVUNIT_DF['BB_count'] = BB_INVUNIT_DF.groupby(['MO','inventoryUnitType'])['inventoryUnitType'].transform('count')
BB_INVUNIT_DF.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\2690477228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BB_INVUNIT_DF['BB_count'] = BB_INVUNIT_DF.groupby(['MO','inventoryUnitType'])['inventoryUnitType'].transform('count')

,MO,configDN,inventoryUnitType,BB_count
11,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,2
13,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC,2
14,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1
21,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,1
22,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1

In [15]:
BB_INVUNIT_DF.to_excel('BB_INVUNIT_DF_4G_NSN.xlsx', index=False)

In [16]:
BB_INVUNIT_DF['BB_map'] = BB_INVUNIT_DF['BB_count'].astype(str) + '_' + BB_INVUNIT_DF['inventoryUnitType']
BB_INVUNIT_DF.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3052174421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BB_INVUNIT_DF['BB_map'] = BB_INVUNIT_DF['BB_count'].astype(str) + '_' + BB_INVUNIT_DF['inventoryUnitType']

,MO,configDN,inventoryUnitType,BB_count,BB_map
11,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,2,2_FBBC
13,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/BBMOD-2,FBBC,2,2_FBBC
14,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
21,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/BBMOD-1,FBBC,1,1_FBBC
22,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF

In [17]:
# Sắp xếp BB_INVUNIT_DF theo inventoryUnitType giảm dần
BB_INVUNIT_DF = BB_INVUNIT_DF.sort_values(by=['inventoryUnitType','MO'], ascending=False)
BB_INVUNIT_DF.head()

,MO,configDN,inventoryUnitType,BB_count,BB_map
75087,PLMN-PLMN/MRBTS-897002,MRBTS-897002/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
74937,PLMN-PLMN/MRBTS-897001,MRBTS-897001/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
75171,PLMN-PLMN/MRBTS-897000,MRBTS-897000/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
75289,PLMN-PLMN/MRBTS-896321,MRBTS-896321/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF
75505,PLMN-PLMN/MRBTS-896320,MRBTS-896320/EQM-1/APEQM-1/CABINET-1/SMOD-1,FSMF,1,1_FSMF

In [18]:
BB_INVUNIT_DF = BB_INVUNIT_DF[['MO', 'BB_map']].drop_duplicates()
BB_INVUNIT_DF.head()

                           MO  BB_map
75087  PLMN-PLMN/MRBTS-897002  1_FSMF
74937  PLMN-PLMN/MRBTS-897001  1_FSMF
75171  PLMN-PLMN/MRBTS-897000  1_FSMF
75289  PLMN-PLMN/MRBTS-896321  1_FSMF
75505  PLMN-PLMN/MRBTS-896320  1_FSMF

In [19]:
BB_INVUNIT_DF['BB_configDN'] = BB_INVUNIT_DF.groupby(['MO'])['BB_map'].transform(lambda x: ' + '.join(x))
BB_INVUNIT_DF.head()

                           MO  BB_map      BB_configDN
75087  PLMN-PLMN/MRBTS-897002  1_FSMF  1_FSMF + 1_FBBC
74937  PLMN-PLMN/MRBTS-897001  1_FSMF  1_FSMF + 1_FBBC
75171  PLMN-PLMN/MRBTS-897000  1_FSMF  1_FSMF + 1_FBBC
75289  PLMN-PLMN/MRBTS-896321  1_FSMF  1_FSMF + 1_FBBC
75505  PLMN-PLMN/MRBTS-896320  1_FSMF  1_FSMF + 1_FBBC

In [20]:
RF_INVUNIT_DF.head()

,MO,configDN,inventoryUnitType
1,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED
4,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU
7,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,FXED
9,PLMN-PLMN/MRBTS-520106,NaN,FXED
27,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/RMOD-1,FXED

In [21]:
RF_INVUNIT_DF.to_excel('RF_INVUNIT_DF_4G_NSN.xlsx', index=False)

In [22]:
RF_INVUNIT_DF['RMOD'] = RF_INVUNIT_DF['configDN'].astype(str).str.replace(r'^.*/', '', regex=True)   
RF_INVUNIT_DF.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3165565714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RF_INVUNIT_DF['RMOD'] = RF_INVUNIT_DF['configDN'].astype(str).str.replace(r'^.*/', '', regex=True)

,MO,configDN,inventoryUnitType,RMOD
1,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
4,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-7,FRGU,RMOD-7
7,PLMN-PLMN/MRBTS-520106,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,FXED,RMOD-1
9,PLMN-PLMN/MRBTS-520106,NaN,FXED,nan
27,PLMN-PLMN/MRBTS-520157,MRBTS-520157/EQM-1/APEQM-1/RMOD-1,FXED,RMOD-1

In [23]:
RF_INVUNIT_DF.drop(columns=['MO'], inplace=True)
RF_INVUNIT_DF.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\411182185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RF_INVUNIT_DF.drop(columns=['MO'], inplace=True)

                             configDN inventoryUnitType    RMOD
1   MRBTS-520106/EQM-1/APEQM-1/RMOD-2              FXED  RMOD-2
4   MRBTS-520106/EQM-1/APEQM-1/RMOD-7              FRGU  RMOD-7
7   MRBTS-520106/EQM-1/APEQM-1/RMOD-1              FXED  RMOD-1
9                                 NaN              FXED     nan
27  MRBTS-520157/EQM-1/APEQM-1/RMOD-1              FXED  RMOD-1

In [24]:
# read CHANNEL
CHANNEL_COLUMNS = ["MO", "antlDN", "direction"]

CHANNEL_DF = read_excel_columns(file, 'CHANNEL', CHANNEL_COLUMNS)
CHANNEL_DF.head()

,MO,antlDN,direction
0,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-7,RX
1,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-7,TX
2,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-8,TX
3,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-8,RX
4,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-1/ANTL-3,TX

In [25]:
CHANNEL_DF = CHANNEL_DF[CHANNEL_DF['direction'].isin(['TX'])]
CHANNEL_DF.head()

,MO,antlDN,direction
1,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-7,TX
2,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-8,TX
4,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-1/ANTL-3,TX
7,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-9,TX
8,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2/ANTL-10,TX

In [26]:
CHANNEL_DF['antlDN'] = CHANNEL_DF['antlDN'].astype(str).str.replace(r'/AN.*$', '', regex=True)   
CHANNEL_DF.head()

,MO,antlDN,direction
1,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX
2,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX
4,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,TX
7,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX
8,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX

In [27]:
df_final_2  = pd.merge(CHANNEL_DF,RF_INVUNIT_DF, left_on='antlDN', right_on='configDN', how='inner')
df_final_2.head()

,MO,antlDN,direction,configDN,inventoryUnitType,RMOD
0,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
1,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
2,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,TX,MRBTS-520106/EQM-1/APEQM-1/RMOD-1,FXED,RMOD-1
3,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2
4,PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,TX,MRBTS-520106/EQM-1/APEQM-1/RMOD-2,FXED,RMOD-2

In [28]:
df_final_2.drop(columns=['antlDN','direction','configDN'], inplace=True)
df_final_2.head()

                                                  MO inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
1  PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-1
3  PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-520106/MNL-1/MNLENT-1/CELLMAPP...              FXED  RMOD-2

In [29]:
df_final_2['MO'] = df_final_2['MO'].astype(str).str.replace('/MNL-1/MNLENT-1/CELLMAPPING-1', '', regex=False)
df_final_2.head()

                                                  MO inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-520106/LCELL-11/CHANNELGROUP-1...              FXED  RMOD-2
1  PLMN-PLMN/MRBTS-520106/LCELL-11/CHANNELGROUP-1...              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-520106/LCELL-12/CHANNELGROUP-1...              FXED  RMOD-1
3  PLMN-PLMN/MRBTS-520106/LCELL-12/CHANNELGROUP-1...              FXED  RMOD-2
4  PLMN-PLMN/MRBTS-520106/LCELL-12/CHANNELGROUP-1...              FXED  RMOD-2

In [30]:
df_final_2['MO'] = df_final_2['MO'].astype(str).str.replace(r'/CHAN.*$', '', regex=True)
df_final_2.drop_duplicates(inplace=True)
df_final_2.head()

                                MO inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-520106/LCELL-11              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-520106/LCELL-12              FXED  RMOD-1
3  PLMN-PLMN/MRBTS-520106/LCELL-12              FXED  RMOD-2
6  PLMN-PLMN/MRBTS-520106/LCELL-13              FXED  RMOD-1
7  PLMN-PLMN/MRBTS-520106/LCELL-13              FXED  RMOD-2

In [31]:
df_final_2['MO'] = df_final_2['MO'].astype(str).str.replace('LCELL', 'LNCEL', regex=False)
df_final_2.head()

                                MO inventoryUnitType    RMOD
0  PLMN-PLMN/MRBTS-520106/LNCEL-11              FXED  RMOD-2
2  PLMN-PLMN/MRBTS-520106/LNCEL-12              FXED  RMOD-1
3  PLMN-PLMN/MRBTS-520106/LNCEL-12              FXED  RMOD-2
6  PLMN-PLMN/MRBTS-520106/LNCEL-13              FXED  RMOD-1
7  PLMN-PLMN/MRBTS-520106/LNCEL-13              FXED  RMOD-2

In [32]:
df_final.head()

,MO,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-11,VUTT98C4BA,198,62150,20 MHz,2T2R,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-12,VUTT98C4BB,200,62150,20 MHz,4T4R,1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-13,VUTT98C4BC,196,62150,20 MHz,2T2R,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-17,VUTT98C4CA,198,62150,10 MHz,2T2R,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNBTS-520106/LNCEL-18,VUTT98C4CB,200,62150,10 MHz,2T2R,50,10,402

In [33]:
df_final['MO'] = df_final['MO'].astype(str).str.replace(r'LNBTS.*/', '', regex=True)
df_final.head()

,MO,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,VUTT98C4BA,198,62150,20 MHz,2T2R,1501,10,378
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,VUTT98C4BB,200,62150,20 MHz,4T4R,1501,10,402
2,PLMN-PLMN/MRBTS-520106/LNCEL-13,VUTT98C4BC,196,62150,20 MHz,2T2R,1501,10,126
3,PLMN-PLMN/MRBTS-520106/LNCEL-17,VUTT98C4CA,198,62150,10 MHz,2T2R,50,10,378
4,PLMN-PLMN/MRBTS-520106/LNCEL-18,VUTT98C4CB,200,62150,10 MHz,2T2R,50,10,402

In [34]:
df_final_3 = pd.merge(df_final_2, df_final, on='MO', how='left')
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0
2,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-2,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0
3,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-1,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0
4,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-2,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0

In [35]:
df_final_3["eNodeB_id"] = df_final_3['MO'].astype(str).str.replace(r'/LNCEL-(\d+)', '', regex=True)
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0,PLMN-PLMN/MRBTS-520106
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106
2,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-2,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106
3,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-1,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106
4,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-2,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106

In [36]:
# Tạo cột Band trong df_final_3 dựa trên giá trị earfcnDL
band_map = {1501: 3, 1874: 3, 50: 1, 3150: 7, 1300:3}
df_final_3['Band'] = df_final_3['earfcnDL'].map(band_map)
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0,PLMN-PLMN/MRBTS-520106,3.0
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0
2,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-2,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0
3,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-1,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0
4,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-2,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0

In [37]:
df_final_3['RF type Count'] = df_final_3.groupby(['eNodeB_id','RMOD','inventoryUnitType','Band'])['inventoryUnitType'].transform('count')
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0,PLMN-PLMN/MRBTS-520106,3.0,4.0
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0,3.0
2,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-2,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0,4.0
3,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-1,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0,3.0
4,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-2,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0,4.0

In [38]:
import numpy as np
df_final_3['RF_Type_Count_Inv'] = np.where(
    df_final_3['RF type Count'] == 1, "1",
    np.where(df_final_3['RF type Count'] == 2, "0.5",
    np.where(df_final_3['RF type Count'] == 4, "0.25",
    np.where(df_final_3['RF type Count'] == 6, "1/6",       
    np.where(df_final_3['RF type Count'] == 3, "1/3", 1/df_final_3['RF type Count'])))))
df_final_3.head(2)

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0,PLMN-PLMN/MRBTS-520106,3.0,4.0,0.25
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0,3.0,1/3

In [39]:
df_final_3['Config_RRU_per_Cell'] = df_final_3['RF_Type_Count_Inv'].astype(str) + '_' + df_final_3['inventoryUnitType'].astype(str)
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell
0,PLMN-PLMN/MRBTS-520106/LNCEL-11,FXED,RMOD-2,VUTT98C4BA,198.0,62150.0,20 MHz,2T2R,1501.0,10.0,378.0,PLMN-PLMN/MRBTS-520106,3.0,4.0,0.25,0.25_FXED
1,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-1,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0,3.0,1/3,1/3_FXED
2,PLMN-PLMN/MRBTS-520106/LNCEL-12,FXED,RMOD-2,VUTT98C4BB,200.0,62150.0,20 MHz,4T4R,1501.0,10.0,402.0,PLMN-PLMN/MRBTS-520106,3.0,4.0,0.25,0.25_FXED
3,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-1,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0,3.0,1/3,1/3_FXED
4,PLMN-PLMN/MRBTS-520106/LNCEL-13,FXED,RMOD-2,VUTT98C4BC,196.0,62150.0,20 MHz,2T2R,1501.0,10.0,126.0,PLMN-PLMN/MRBTS-520106,3.0,4.0,0.25,0.25_FXED

In [40]:
df_final_3['Config_RRU'] = (df_final_3.groupby(['MO','name'])['Config_RRU_per_Cell'].transform(lambda x: "+".join(map(str, x))))

In [41]:
df_final_3 = df_final_3.sort_values(by='RMOD',ascending=True)
df_final_3['Subrack'] = (df_final_3.groupby(['MO','name'])['RMOD'].transform(lambda x: "+".join(map(str, x))))
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack
30634,PLMN-PLMN/MRBTS-894005/LNCEL-13,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,642.0,PLMN-PLMN/MRBTS-894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1
11389,PLMN-PLMN/MRBTS-562484/LNCEL-12,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,222.0,PLMN-PLMN/MRBTS-562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2
22792,PLMN-PLMN/MRBTS-600622/LNCEL-43,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,12.0,PLMN-PLMN/MRBTS-600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2
11392,PLMN-PLMN/MRBTS-562484/LNCEL-13,FXED,RMOD-1,DNTN45C4BC,50.0,65160.0,20 MHz,4T4R,1501.0,10.0,384.0,PLMN-PLMN/MRBTS-562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2
11393,PLMN-PLMN/MRBTS-562951/LNCEL-11,FXED,RMOD-1,DNDQ00M4BA,222.0,65110.0,20 MHz,2T2R,1501.0,10.0,66.0,PLMN-PLMN/MRBTS-562951,3.0,4.0,0.25,0.25_FXED,0.25_FXED,RMOD-1

In [42]:
df_final_3['localcell ID'] = df_final_3['MO'].replace(r'^.*-', '', regex=True)

In [43]:

df_final_3['eNodeB_id'] = df_final_3['eNodeB_id'].replace(r'^.*-', '', regex=True)
df_final_3['MO'] = df_final_3['MO'].replace(r'/LN.*', '', regex=True)
df_final_3.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,rootSeqIndex,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,localcell ID
30634,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,642.0,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13
11389,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,222.0,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12
22792,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,12.0,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43
11392,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BC,50.0,65160.0,20 MHz,4T4R,1501.0,10.0,384.0,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,13
11393,PLMN-PLMN/MRBTS-562951,FXED,RMOD-1,DNDQ00M4BA,222.0,65110.0,20 MHz,2T2R,1501.0,10.0,66.0,562951,3.0,4.0,0.25,0.25_FXED,0.25_FXED,RMOD-1,11

In [44]:
df_final_3['Vendor']= 'Nokia'

In [45]:
df_final_4 = pd.merge(df_final_3, BB_INVUNIT_DF[['MO', 'BB_configDN']], on='MO', how='left')
df_final_4.head()

,MO,inventoryUnitType,RMOD,name,phyCellId,tac,dlChBw,dlMimoMode,earfcnDL,prachCS,...,eNodeB_id,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,localcell ID,Vendor,BB_configDN
0,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
1,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
2,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
3,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
4,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,...,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43,Nokia,1_FSMF + 1_FBBC

In [46]:
rename_columns = {'name':'Cell Name', 'phyCellId':'PCI', 'earfcnDL':'EARFCN',
                  'dlChBw':'Bandwidth', 'dlMimoMode':'MIMO','rootSeqIndex':'RSI', 'tac':'TAC',
                  'BB_configDN':'Config_BBU','prachCS':'Cell Radius','localcell ID':'Local Cell ID','MO':'Base Station Name',
                  'eNodeB_id':'eNodeB ID'
                  } 
df_final_4.rename(columns=rename_columns, inplace=True)
df_final_4.head()

,Base Station Name,inventoryUnitType,RMOD,Cell Name,PCI,TAC,Bandwidth,MIMO,EARFCN,Cell Radius,...,eNodeB ID,Band,RF type Count,RF_Type_Count_Inv,Config_RRU_per_Cell,Config_RRU,Subrack,Local Cell ID,Vendor,Config_BBU
0,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
1,PLMN-PLMN/MRBTS-894005,FXED,RMOD-1,TYMC48C4BC,301.0,62840.0,20 MHz,2T2R,1501.0,10.0,...,894005,3.0,6.0,1/6,1/6_FXED,1/6_FXED,RMOD-1,13,Nokia,1_FSMF + 1_FBBC
2,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
3,PLMN-PLMN/MRBTS-562484,FXED,RMOD-1,DNTN45C4BB,48.0,65160.0,20 MHz,4T4R,1501.0,10.0,...,562484,3.0,3.0,1/3,1/3_FXED,1/3_FXED+1/3_FXED,RMOD-1+RMOD-2,12,Nokia,1_FSMF + 1_FBBC
4,PLMN-PLMN/MRBTS-600622,FXED,RMOD-1,TYTR78C4BL,417.0,62890.0,15 MHz,2T2R,1874.0,10.0,...,600622,3.0,6.0,1/6,1/6_FXED,1/6_FXED+1/6_FXED,RMOD-1+RMOD-2,43,Nokia,1_FSMF + 1_FBBC

In [47]:
df_final_Nokia = df_final_4[['Base Station Name', 'Local Cell ID', 'Cell Name', 'Band', 'EARFCN',
       'Bandwidth', 'MIMO','eNodeB ID', 'TAC', 'PCI', 'RSI', 'Cell Radius', 'Vendor', 'Subrack', 'Config_BBU', 'Config_RRU']]
df_final_Nokia.head()

,Base Station Name,Local Cell ID,Cell Name,Band,EARFCN,Bandwidth,MIMO,eNodeB ID,TAC,PCI,RSI,Cell Radius,Vendor,Subrack,Config_BBU,Config_RRU
0,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
1,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
2,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
3,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
4,PLMN-PLMN/MRBTS-600622,43,TYTR78C4BL,3.0,1874.0,15 MHz,2T2R,600622,62890.0,417.0,12.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/6_FXED+1/6_FXED

In [48]:
df_final_Nokia['Local Cell ID']= df_final_Nokia['Local Cell ID'].astype(int)
df_final_Nokia['eNodeB ID']= df_final_Nokia['eNodeB ID'].astype(int)
df_final_Nokia.drop_duplicates(inplace=True)
df_final_Nokia.head()

C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia['Local Cell ID']= df_final_Nokia['Local Cell ID'].astype(int)
C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia['eNodeB ID']= df_final_Nokia['eNodeB ID'].astype(int)
C:\Users\Chinhnq\AppData\Local\Temp\ipykernel_25040\3055319718.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_Nokia.drop_duplicates(inplace=True)

,Base Station Name,Local Cell ID,Cell Name,Band,EARFCN,Bandwidth,MIMO,eNodeB ID,TAC,PCI,RSI,Cell Radius,Vendor,Subrack,Config_BBU,Config_RRU
0,PLMN-PLMN/MRBTS-894005,13,TYMC48C4BC,3.0,1501.0,20 MHz,2T2R,894005,62840.0,301.0,642.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,1/6_FXED
2,PLMN-PLMN/MRBTS-562484,12,DNTN45C4BB,3.0,1501.0,20 MHz,4T4R,562484,65160.0,48.0,222.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
4,PLMN-PLMN/MRBTS-600622,43,TYTR78C4BL,3.0,1874.0,15 MHz,2T2R,600622,62890.0,417.0,12.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/6_FXED+1/6_FXED
6,PLMN-PLMN/MRBTS-562484,13,DNTN45C4BC,3.0,1501.0,20 MHz,4T4R,562484,65160.0,50.0,384.0,10.0,Nokia,RMOD-1+RMOD-2,1_FSMF + 1_FBBC,1/3_FXED+1/3_FXED
8,PLMN-PLMN/MRBTS-562951,11,DNDQ00M4BA,3.0,1501.0,20 MHz,2T2R,562951,65110.0,222.0,66.0,10.0,Nokia,RMOD-1,1_FSMF + 1_FBBC,0.25_FXED

In [49]:
df_final_Nokia.to_excel('4G_NSN_Inventory_Output.xlsx', index=False)