# file Export_MultiTable_5G bao gồm các sheet
 1.NRCELL
 2.INVUNIT

In [70]:
import pandas as pd

In [71]:
def read_excel_columns(file_path, sheet,columns):
   
    df = pd.read_excel(file_path, sheet_name=sheet, usecols=columns,  engine='openpyxl')

    return df

In [72]:
# read NRCELL sheet
NRCELL_COLUMNS = ["MO", "name", "lcrId",'physCellId','freqBandIndicatorNR','nrarfcn','chBw','configuredEpsTac',
                  'gscnOrSsPbchArfcn','mMimoAntArrayMode','ssbScs','prachRootSequenceIndex','frRefList','modDNList','ulDlDataSlotRatio']
file = 'Export_MultiTable_5G.xlsx'
nrcell_df = read_excel_columns(file, 'NRCELL', NRCELL_COLUMNS)
nrcell_df.head()

,MO,name,chBw,configuredEpsTac,frRefList,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,modDNList,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,270,5,30 KHz,1/4
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,272,25,30 KHz,1/4
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-3,77,8089,53,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,271,15,30 KHz,1/4
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,490,10,30 KHz,1/4
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,390,20,30 KHz,1/4

In [73]:
# read INVUNIT
INVUNIT_COLUMNS = ["configDN", "inventoryUnitType"]

INVUNIT_DF = read_excel_columns(file, 'INVUNIT', INVUNIT_COLUMNS)
INVUNIT_DF.dropna(inplace=True)
INVUNIT_DF.head()

,configDN,inventoryUnitType
0,MRBTS-7052891/EQM-1/APEQM-1/CABINET-1,AMIA AirScale Indoor Subrack
8,MRBTS-7052891/EQM-1/APEQM-1/RMOD-1,AQQV
9,MRBTS-7052891/EQM-1/APEQM-1/RMOD-3,AQQV
10,MRBTS-7052891/EQM-1/APEQM-1/RMOD-2,AQQV
11,MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,ABIP AirScale Capacity

In [74]:
df_final = pd.merge(nrcell_df, INVUNIT_DF, left_on='modDNList', right_on='configDN', how='left')
df_final.drop(columns=['configDN'], inplace=True)
df_final.rename(columns={'inventoryUnitType':'BBU'}, inplace=True)
df_final.head()

,MO,name,chBw,configuredEpsTac,frRefList,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,modDNList,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,270,5,30 KHz,1/4,ABIP AirScale Capacity
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,272,25,30 KHz,1/4,ABIP AirScale Capacity
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-3,77,8089,53,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,271,15,30 KHz,1/4,ABIP AirScale Capacity
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,490,10,30 KHz,1/4,ABIP AirScale Capacity
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,390,20,30 KHz,1/4,ABIP AirScale Capacity

In [75]:
df_final = pd.merge(df_final, INVUNIT_DF, left_on='frRefList', right_on='configDN', how='left')
df_final.drop(columns=['configDN'], inplace=True)
df_final.rename(columns={'inventoryUnitType':'RRU'}, inplace=True)
df_final.head()

,MO,name,chBw,configuredEpsTac,frRefList,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,modDNList,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,270,5,30 KHz,1/4,ABIP AirScale Capacity,AQQV
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,272,25,30 KHz,1/4,ABIP AirScale Capacity,AQQV
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-3,77,8089,53,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,271,15,30 KHz,1/4,ABIP AirScale Capacity,AQQV
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,490,10,30 KHz,1/4,ABIP AirScale Capacity,AVQG
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,390,20,30 KHz,1/4,ABIP AirScale Capacity,AVQG

In [76]:
df_final['RMOD'] = df_final['frRefList'].astype(str).str.replace(r'^.*/', '', regex=True)  
df_final.head()

,MO,name,chBw,configuredEpsTac,frRefList,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,modDNList,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,270,5,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-1
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,272,25,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-2
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,MRBTS-7052891/EQM-1/APEQM-1/RMOD-3,77,8089,53,Full 32TRX Array (2x8x2),MRBTS-7052891/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,271,15,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-3
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-1,77,8089,51,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,490,10,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-1
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,MRBTS-7052604/EQM-1/APEQM-1/RMOD-2,77,8089,52,Full 64TRX Array (4x8x2),MRBTS-7052604/EQM-1/APEQM-1/CABINET-1/BBMOD-1,656666,390,20,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-2

In [77]:
df_final.drop(columns=['frRefList','modDNList'],inplace= True)
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,77,8089,51,Full 32TRX Array (2x8x2),656666,270,5,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-1
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,77,8089,52,Full 32TRX Array (2x8x2),656666,272,25,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-2
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,77,8089,53,Full 32TRX Array (2x8x2),656666,271,15,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-3
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,77,8089,51,Full 64TRX Array (4x8x2),656666,490,10,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-1
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,77,8089,52,Full 64TRX Array (4x8x2),656666,390,20,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-2

In [78]:
df_final['mMimoAntArrayMode'].unique()

array(['Full 32TRX Array (2x8x2)', 'Full 64TRX Array (4x8x2)'],
      dtype=object)

In [79]:
replacement_dict = {
    'Full 32TRX Array (2x8x2)': '32T32R',
    'Full 64TRX Array (4x8x2)': '64T64R',}
df_final['mMimoAntArrayMode'] = df_final['mMimoAntArrayMode'].replace(replacement_dict)
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-1
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-2
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-3
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-1
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-2

In [80]:
df_final['freqBandIndicatorNR']='N77'
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-1
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-2
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP AirScale Capacity,AQQV,RMOD-3
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-1
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP AirScale Capacity,AVQG,RMOD-2

In [81]:
replacement_dict = {
    'ABIP AirScale Capacity': 'ABIP'}
df_final['BBU'] = df_final['BBU'].replace(replacement_dict)
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP,AQQV,RMOD-1
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP,AQQV,RMOD-2
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP,AQQV,RMOD-3
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP,AVQG,RMOD-1
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP,AVQG,RMOD-2

In [82]:
df_final['gNodeB ID'] = df_final['MO'].astype(str).str.replace(r'/NRCEL.*', '', regex=True).str.replace(r'^.*-', '', regex=True)
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD,gNodeB ID
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP,AQQV,RMOD-1,7052891
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP,AQQV,RMOD-2,7052891
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP,AQQV,RMOD-3,7052891
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP,AVQG,RMOD-1,7052604
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP,AVQG,RMOD-2,7052604

In [83]:
df_final['Base Station Name'] = df_final['name'].astype(str).str.slice(0,6)
df_final.head()

,MO,name,chBw,configuredEpsTac,freqBandIndicatorNR,gscnOrSsPbchArfcn,lcrId,mMimoAntArrayMode,nrarfcn,physCellId,prachRootSequenceIndex,ssbScs,ulDlDataSlotRatio,BBU,RRU,RMOD,gNodeB ID,Base Station Name
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP,AQQV,RMOD-1,7052891,TGCB56
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP,AQQV,RMOD-2,7052891,TGCB56
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP,AQQV,RMOD-3,7052891,TGCB56
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP,AVQG,RMOD-1,7052604,TGCB01
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP,AVQG,RMOD-2,7052604,TGCB01

In [87]:
re_name_dict = {
    'name':'Cell Name','configuredEpsTac':'TAC','physCellId':'PCI',
    'nrarfcn':'DL NARFCN','chBw':'DL Bandwidth','gscnOrSsPbchArfcn':'SSB FP',
    'mMimoAntArrayMode':'TxRx Mode','ssbScs':'SCS (KHz)','freqBandIndicatorNR':'Band','prachRootSequenceIndex':'RSI',
    'ulDlDataSlotRatio':'Slot Assignment',"lcrId":'Cell ID'}
df_final.rename(columns=re_name_dict, inplace=True)
df_final.head()

,MO,Cell Name,DL Bandwidth,TAC,Band,SSB FP,Cell ID,TxRx Mode,DL NARFCN,PCI,RSI,SCS (KHz),Slot Assignment,BBU,RRU,RMOD,gNodeB ID,Base Station Name
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,1/4,ABIP,AQQV,RMOD-1,7052891,TGCB56
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,1/4,ABIP,AQQV,RMOD-2,7052891,TGCB56
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,1/4,ABIP,AQQV,RMOD-3,7052891,TGCB56
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,1/4,ABIP,AVQG,RMOD-1,7052604,TGCB01
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,1/4,ABIP,AVQG,RMOD-2,7052604,TGCB01

In [88]:
replacement_dict = {
    '1/4': '8_2_DDDDDDDSUU'}
df_final['Slot Assignment'] = df_final['Slot Assignment'].replace(replacement_dict)
df_final.head()

,MO,Cell Name,DL Bandwidth,TAC,Band,SSB FP,Cell ID,TxRx Mode,DL NARFCN,PCI,RSI,SCS (KHz),Slot Assignment,BBU,RRU,RMOD,gNodeB ID,Base Station Name
0,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-51,TGCB56C5SA,100MHz,48000,N77,8089,51,32T32R,656666,270,5,30 KHz,8_2_DDDDDDDSUU,ABIP,AQQV,RMOD-1,7052891,TGCB56
1,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-52,TGCB56C5SB,100MHz,48000,N77,8089,52,32T32R,656666,272,25,30 KHz,8_2_DDDDDDDSUU,ABIP,AQQV,RMOD-2,7052891,TGCB56
2,PLMN-PLMN/MRBTS-7052891/NRBTS-7052891/NRCELL-53,TGCB56C5SC,100MHz,48000,N77,8089,53,32T32R,656666,271,15,30 KHz,8_2_DDDDDDDSUU,ABIP,AQQV,RMOD-3,7052891,TGCB56
3,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-51,TGCB01M5SA,100MHz,48000,N77,8089,51,64T64R,656666,490,10,30 KHz,8_2_DDDDDDDSUU,ABIP,AVQG,RMOD-1,7052604,TGCB01
4,PLMN-PLMN/MRBTS-7052604/NRBTS-7052604/NRCELL-52,TGCB01M5SB,100MHz,48000,N77,8089,52,64T64R,656666,390,20,30 KHz,8_2_DDDDDDDSUU,ABIP,AVQG,RMOD-2,7052604,TGCB01

In [91]:
df_final = df_final[['Base Station Name','Cell ID','Cell Name','PCI','Band','DL NARFCN','DL Bandwidth','SCS (KHz)',
                     'Slot Assignment','TAC','SSB FP','RSI','TxRx Mode','RMOD','BBU','RRU','gNodeB ID']]
df_final.head()

,Base Station Name,Cell ID,Cell Name,PCI,Band,DL NARFCN,DL Bandwidth,SCS (KHz),Slot Assignment,TAC,SSB FP,RSI,TxRx Mode,RMOD,BBU,RRU,gNodeB ID
0,TGCB56,51,TGCB56C5SA,270,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,5,32T32R,RMOD-1,ABIP,AQQV,7052891
1,TGCB56,52,TGCB56C5SB,272,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,25,32T32R,RMOD-2,ABIP,AQQV,7052891
2,TGCB56,53,TGCB56C5SC,271,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,15,32T32R,RMOD-3,ABIP,AQQV,7052891
3,TGCB01,51,TGCB01M5SA,490,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,10,64T64R,RMOD-1,ABIP,AVQG,7052604
4,TGCB01,52,TGCB01M5SB,390,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,20,64T64R,RMOD-2,ABIP,AVQG,7052604

In [94]:
df_final['Vendor'] = 'Nokia'
df_final.head()

,Base Station Name,Cell ID,Cell Name,PCI,Band,DL NARFCN,DL Bandwidth,SCS (KHz),Slot Assignment,TAC,SSB FP,RSI,TxRx Mode,RMOD,BBU,RRU,gNodeB ID,Vendor
0,TGCB56,51,TGCB56C5SA,270,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,5,32T32R,RMOD-1,ABIP,AQQV,7052891,Nokia
1,TGCB56,52,TGCB56C5SB,272,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,25,32T32R,RMOD-2,ABIP,AQQV,7052891,Nokia
2,TGCB56,53,TGCB56C5SC,271,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,15,32T32R,RMOD-3,ABIP,AQQV,7052891,Nokia
3,TGCB01,51,TGCB01M5SA,490,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,10,64T64R,RMOD-1,ABIP,AVQG,7052604,Nokia
4,TGCB01,52,TGCB01M5SB,390,N77,656666,100MHz,30 KHz,8_2_DDDDDDDSUU,48000,8089,20,64T64R,RMOD-2,ABIP,AVQG,7052604,Nokia

In [93]:
df_final.to_excel('5G_NSN_inventory_output.xlsx', index=False)